### ISSUE TITLE
FOV cheat engine 

### ISSUE THREAD

**Issue by forz0i** [Spawnova/ShinsMemoryClass#1]
Hello Spawnova
Plase add script withe cheat engine Fov distance caméra for 3 games 
1 From dusk till down
, I'm looking form dusk to dawn solution. After several failed conversions
and a lack of experience, I decided to find the appropriate code to change
the camera distance.
I edited the file and it works fine on Windows 10
I hope you find the code with the cheat engine
Change the distance of the camera's field of view
Thank you very much and sincere appreciation for your efforts, my friend
link download:
https://www.mediafire.com/file/574pgen7e5iszy5/From-Dusk-Till-Dawn+win+10.rar/file
2 bad boys 2
I sometimes encounter difficulties. I'm not very knowledgeable and I'm
missing an explanation on how to deal with the "cheat engine" program and
how to fix and find FOV in game DX9. There is a request, with your
permission, that I would like to change FOV to other valu of bad boys 2 at
present, change viewing distance, like spyhunter with cheat engine
The bad boys 2 engine is used direct x 9.0
link downolad game full crack ;
https://www.mediafire.com/file/yuegcvgt9njdgyf/Bad_Boys_2_pc_g.rar/file
Dead to rights 2 :https://steamunlocked.net/dead-to-rights-2-free-download/
Crack english x64:https://gamecopyworld.com/games/pc_dead_to_rights_2.shtml
Plase help me to add fov withe cheat engine code

Bad boys 2 dx9. 0
dead to rights 2 dx9. 0c
From dusk till dawn dx8.0a
Cheat engine fov valeur  and near plan

**Comment by forz0i** [comment]
Bad boys 2 and From dusk till dawn  pc with Window mod fix  :https://youtu.be/gc3aDY7Zesc?si=2JYHaSdfcV2h2nqa
Dead to rights 2 pc play Window mod  édit. Txt in game fload  Window = 1  full screen =0

**Comment by Spawnova** [comment]
Hey there, unfortunately I don't have any available time for requests like that, seeing as those are older games it's very possible people have already made patches/mods for them though.
This github is primarily for issues or suggestions for the autohotkey script, I hope you understand and I'm sorry I'm unable to help with your request

**Comment by forz0i** [comment]
It is possible for you to download a video, comment on it, and find the Matrix FOV in other relative languages ​​DX8 and DX9. What functions do you have on Windows 10? 
I'm looking for more money

**Comment by forz0i** [comment]
Plase help me 🙏🏻🙏🏻🙏🏻 how find fov with classic game dx8 and dx9  for the 3 game
Bad boys 2 dx9
From dusk till dawn dx8
Dead to rights 2  dx9
Plase tutorial with cheat engine help me my hero 👽🙏🏻🙏🏻
